title: Leonardo Trujillo — Research & Teaching
description: Researcher in computational neuroscience and applied mathematics. Projects, publications, and teaching.
url: ""  
baseurl: ""  
markdown: kramdown
theme: null
