# Site settings
title: "Mechanistic modelling of biological systems"
name: "Leonardo TRUJILLO"
description: "Associate Professor (MCU) in Applied Mathematics, INSA Lyon"
url: "https://leotru.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"   # <-- opcional

# Language & permalinks
locale: "en"
permalink: /:categories/:title/

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed

# >>> IMPORTANT <<<
include:
  - _pages                # <-- para que publique /about/, /research/, etc.

# Author profile
author:
  name: "Leonardo TRUJILLO"
  avatar: "/assets/images/avatar.jpg"
  bio: "Associate Professor in Applied Mathematics"
  email: "leonardo.trujillo@gmail.com"
  location: "Lyon, France"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=_L0Cq3YAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0001-9995-4135"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leotru"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.inria.fr/letrujil"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/trujilloleonardo/"
    - label: "X"
      icon: "fab fa-x-twitter"
      url: "https://x.com/entropiacero"

# Defaults for pages/posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
